//
// ActDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ActDTO

import Vapor


public final class ActDTO: Content {

    /** id-документу */
    public var `id`: Int64?
    /** ЄДРПОУ-розпорядника */
    public var edrpou: String?
    /** Номер документу */
    public var documentNumber: String?
    /** Дата укладання документу */
    public var documentDate: String?
    /** Дата підписання (оприлюднення) */
    public var signDate: String?
    public var signature: SignatureDTO?
    /** Вартість документу */
    public var amount: Double?
    /** Валюта документу */
    public var currency: String?
    /** Еквівалент, грн. (для валютних документів) */
    public var currencyAmountUAH: Double?
    /** Контрагенти */
    public var contractors: [ContractorDTO]?
    /** id-договору (\&quot;батьківський\&quot; договір для акта) */
    public var parentId: Int64?
    /** з ПДВ/без ПДВ у вартості акта */
    public var pdvInclude: Bool?
    /** сума ПДВ у вартості акта */
    public var pdvAmount: Double?
    /** Специфікації */
    public var specifications: [SpecificationDTO]?
    /** з ПДВ/ без ПДВ у ціні за одиницю специфікації */
    public var isCpvVat: Bool?
    /** Масив кодів за ДК 021:2015 */
    public var procurementItems: [Procurement]?

    public init(`id`: Int64?, edrpou: String?, documentNumber: String?, documentDate: String?, signDate: String?, signature: SignatureDTO?, amount: Double?, currency: String?, currencyAmountUAH: Double?, contractors: [ContractorDTO]?, parentId: Int64?, pdvInclude: Bool?, pdvAmount: Double?, specifications: [SpecificationDTO]?, isCpvVat: Bool?, procurementItems: [Procurement]?) { 
        self.`id` = `id`
        self.edrpou = edrpou
        self.documentNumber = documentNumber
        self.documentDate = documentDate
        self.signDate = signDate
        self.signature = signature
        self.amount = amount
        self.currency = currency
        self.currencyAmountUAH = currencyAmountUAH
        self.contractors = contractors
        self.parentId = parentId
        self.pdvInclude = pdvInclude
        self.pdvAmount = pdvAmount
        self.specifications = specifications
        self.isCpvVat = isCpvVat
        self.procurementItems = procurementItems
    }
}
