//
// AddendumReasonDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.AddendumReasonDTO

import Vapor


public final class AddendumReasonDTO: Content {

    public var reasonId: Int?

    public init(reasonId: Int?) { 
        self.reasonId = reasonId
    }
}
