//
// AddendumDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.AddendumDTO

import Vapor


public final class AddendumDTO: Content {

    /** id-документу */
    public var `id`: Int64?
    /** ЄДРПОУ-розпорядника */
    public var edrpou: String?
    /** Номер документу */
    public var documentNumber: String?
    /** Дата укладання документу */
    public var documentDate: String?
    /** Дата підписання (оприлюднення) */
    public var signDate: String?
    public var signature: SignatureDTO?
    /** Вартість документу */
    public var amount: Double?
    /** Валюта документу */
    public var currency: String?
    /** Еквівалент, грн. (для валютних документів) */
    public var currencyAmountUAH: Double?
    /** Контрагенти */
    public var contractors: [ContractorDTO]?
    /** id-договору (\&quot;батьківський\&quot; договір для додаткової угоди) */
    public var parentId: Int64?
    /** строк дії дод.угоди з */
    public var fromDate: String?
    /** строк дії дод.угоди по */
    public var toDate: String?
    /** Безстроковий */
    public var noTerm: Bool?
    /** предмет додаткової угоди */
    public var subject: String?
    /** сума додаткової угоди */
    public var amountIncrease: Double?
    /** з ПДВ/без ПДВ скоригована вартість основного договору */
    public var pdvInclude: Bool?
    /** сума ПДВ в скоригованій вартості основного договору */
    public var pdvAmount: Double?
    /** Тип коригування вартості основного договору: 0: сума додаткової угоди зменшує вартість основного договору, 1: сума додаткової угоди збільшує вартість основного договору, 2: сума додаткової угоди не змінює вартість основного договору */
    public var correctionType: Int?
    /** з ПДВ/без ПДВ сума додаткової угоди */
    public var isCorrectionWithPDF: Bool?
    /** сума ПДВ у сумі додаткової угоди */
    public var correctionVATValue: Double?
    /** підстава укладення додаткової угоди: 0: зміна предмету, 1: зміна ціни, 2: зміна терміну, 99: інше */
    public var reasonTypes: [AddendumReasonDTO]?
    /** деталізація підстави \&quot;99:інше\&quot; */
    public var reasonOtherComment: String?
    /** Специфікації */
    public var specifications: [SpecificationDTO]?
    /** з ПДВ/ без ПДВ у ціні за одиницю специфікації */
    public var isCpvVat: Bool?
    /** Масив кодів за ДК 021:2015 */
    public var procurementItems: [Procurement]?

    public init(`id`: Int64?, edrpou: String?, documentNumber: String?, documentDate: String?, signDate: String?, signature: SignatureDTO?, amount: Double?, currency: String?, currencyAmountUAH: Double?, contractors: [ContractorDTO]?, parentId: Int64?, fromDate: String?, toDate: String?, noTerm: Bool?, subject: String?, amountIncrease: Double?, pdvInclude: Bool?, pdvAmount: Double?, correctionType: Int?, isCorrectionWithPDF: Bool?, correctionVATValue: Double?, reasonTypes: [AddendumReasonDTO]?, reasonOtherComment: String?, specifications: [SpecificationDTO]?, isCpvVat: Bool?, procurementItems: [Procurement]?) { 
        self.`id` = `id`
        self.edrpou = edrpou
        self.documentNumber = documentNumber
        self.documentDate = documentDate
        self.signDate = signDate
        self.signature = signature
        self.amount = amount
        self.currency = currency
        self.currencyAmountUAH = currencyAmountUAH
        self.contractors = contractors
        self.parentId = parentId
        self.fromDate = fromDate
        self.toDate = toDate
        self.noTerm = noTerm
        self.subject = subject
        self.amountIncrease = amountIncrease
        self.pdvInclude = pdvInclude
        self.pdvAmount = pdvAmount
        self.correctionType = correctionType
        self.isCorrectionWithPDF = isCorrectionWithPDF
        self.correctionVATValue = correctionVATValue
        self.reasonTypes = reasonTypes
        self.reasonOtherComment = reasonOtherComment
        self.specifications = specifications
        self.isCpvVat = isCpvVat
        self.procurementItems = procurementItems
    }
}
