//
// AddressDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.AddressDTO

import Vapor


public final class AddressDTO: Content {

    public var city: String?
    public var countryId: Int64?
    public var countryName: String?
    public var district: String?
    public var districtCity: String?
    public var house: String?
    public var housing: String?
    public var office: String?
    public var regionId: Int64?
    public var regionName: String?
    public var street: String?

    public init(city: String?, countryId: Int64?, countryName: String?, district: String?, districtCity: String?, house: String?, housing: String?, office: String?, regionId: Int64?, regionName: String?, street: String?) { 
        self.city = city
        self.countryId = countryId
        self.countryName = countryName
        self.district = district
        self.districtCity = districtCity
        self.house = house
        self.housing = housing
        self.office = office
        self.regionId = regionId
        self.regionName = regionName
        self.street = street
    }
}
