//
// AggregateMapDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.AggregateMapDTO

import Vapor


public final class AggregateMapDTO: Content {

    public var legendsDtoList: [LegendDTO]?
    public var listTreasureDataDTO: [AggregateTreasureDataDTO]?

    public init(legendsDtoList: [LegendDTO]?, listTreasureDataDTO: [AggregateTreasureDataDTO]?) { 
        self.legendsDtoList = legendsDtoList
        self.listTreasureDataDTO = listTreasureDataDTO
    }
}
