//
// AggregateTreasureDataDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.AggregateTreasureDataDTO

import Vapor


public final class AggregateTreasureDataDTO: Content {

    public var amount: Decimal?
    public var colorId: Int?
    public var regionId: Int?
    public var regionName: String?
    public var transactionsCount: Int?

    public init(amount: Decimal?, colorId: Int?, regionId: Int?, regionName: String?, transactionsCount: Int?) { 
        self.amount = amount
        self.colorId = colorId
        self.regionId = regionId
        self.regionName = regionName
        self.transactionsCount = transactionsCount
    }
}
