//
// CabinetRegDynamic.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.CabinetRegDynamic

import Vapor


public final class CabinetRegDynamic: Content {

    public var amount: Int64?
    public var date: String?

    public init(amount: Int64?, date: String?) { 
        self.amount = amount
        self.date = date
    }
}
