//
// ContractDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ContractDTO

import Vapor


public final class ContractDTO: Content {

    /** id-документу */
    public var `id`: Int64?
    /** ЄДРПОУ-розпорядника */
    public var edrpou: String?
    /** Номер документу */
    public var documentNumber: String?
    /** Дата укладання документу */
    public var documentDate: String?
    /** Дата підписання (оприлюднення) */
    public var signDate: String?
    public var signature: SignatureDTO?
    /** Вартість документу */
    public var amount: Double?
    /** Валюта документу */
    public var currency: String?
    /** Еквівалент, грн. (для валютних документів) */
    public var currencyAmountUAH: Double?
    /** Контрагенти */
    public var contractors: [ContractorDTO]?
    /** Строк дії договору з */
    public var fromDate: String?
    /** Строк дії договору по */
    public var toDate: String?
    /** Предмет договору */
    public var subject: String?
    /** Безстроковий */
    public var noTerm: Bool?
    /** з ПДВ/без ПДВ у вартості договору */
    public var pdvInclude: Bool?
    /** Сума ПДВ у вартості договору */
    public var pdvAmount: Double?
    /** Тендерна процедура закупівлі */
    public var tender: Bool?
    /** Обґрунтування відсутності тендерної процедури закупівлі */
    public var reason: String?
    /** Специфікації */
    public var specifications: [SpecificationDTO]?
    /** з ПДВ/без ПДВ у ціні за одиницю специфікац */
    public var isCpvVat: Bool?
    /** Масив кодів за ДК 021:2015 */
    public var procurementItems: [Procurement]?

    public init(`id`: Int64?, edrpou: String?, documentNumber: String?, documentDate: String?, signDate: String?, signature: SignatureDTO?, amount: Double?, currency: String?, currencyAmountUAH: Double?, contractors: [ContractorDTO]?, fromDate: String?, toDate: String?, subject: String?, noTerm: Bool?, pdvInclude: Bool?, pdvAmount: Double?, tender: Bool?, reason: String?, specifications: [SpecificationDTO]?, isCpvVat: Bool?, procurementItems: [Procurement]?) { 
        self.`id` = `id`
        self.edrpou = edrpou
        self.documentNumber = documentNumber
        self.documentDate = documentDate
        self.signDate = signDate
        self.signature = signature
        self.amount = amount
        self.currency = currency
        self.currencyAmountUAH = currencyAmountUAH
        self.contractors = contractors
        self.fromDate = fromDate
        self.toDate = toDate
        self.subject = subject
        self.noTerm = noTerm
        self.pdvInclude = pdvInclude
        self.pdvAmount = pdvAmount
        self.tender = tender
        self.reason = reason
        self.specifications = specifications
        self.isCpvVat = isCpvVat
        self.procurementItems = procurementItems
    }
}
