//
// ContractorType.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ContractorType

import Vapor


public final class ContractorType: Content {

    public var code: Int?
    public var type: String?

    public init(code: Int?, type: String?) { 
        self.code = code
        self.type = type
    }
}
