//
// ContractorDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ContractorDTO

import Vapor


public final class ContractorDTO: Content {

    public var address: AddressDTO?
    /** Тип контрагента: 0: фізична особа, 1: фізична особа-підприємець, 2: юридична особа, -1: невизначений */
    public var contractorType: Int?
    /** Ім&#x27;я керівника контрагента */
    public var firstName: String?
    public var identifier: String?
    /** Прізвище керівника контрагента */
    public var lastName: String?
    /** По батькові керівника контрагента */
    public var middleName: String?
    /** Найменування контрагента */
    public var name: String?

    public init(address: AddressDTO?, contractorType: Int?, firstName: String?, identifier: String?, lastName: String?, middleName: String?, name: String?) { 
        self.address = address
        self.contractorType = contractorType
        self.firstName = firstName
        self.identifier = identifier
        self.lastName = lastName
        self.middleName = middleName
        self.name = name
    }
}
