//
// Country.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Country

import Vapor


public final class Country: Content {

    /** Id країни */
    public var `id`: Int?
    /** Код країни */
    public var code: String?

    public init(`id`: Int?, code: String?) { 
        self.`id` = `id`
        self.code = code
    }
}
