//
// CurrencyDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.CurrencyDTO

import Vapor


public final class CurrencyDTO: Content {

    public var code: String?
    public var `id`: Int?
    public var title: String?

    public init(code: String?, `id`: Int?, title: String?) { 
        self.code = code
        self.`id` = `id`
        self.title = title
    }
}
