//
// DicKekDto.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DicKekDto

import Vapor


public final class DicKekDto: Content {

    /** ID запису */
    public var `id`: Int64?
    /** Код видатків бюджету за  економічною класифікацією */
    public var code: String?
    /** Найменування видатків бюджету за  економічною класифікацією */
    public var name: String?
    /** Батьківський код */
    public var parentCode: String?
    /** Рівень коду в ієрархії */
    public var level: Int?
    /** Ознака детальний */
    public var details: Bool?
    /** Дата початку дії запису */
    public var beginDate: String?
    /** Підстава для створення запису */
    public var beginDoc: String?
    /** Дата припинення дії запису */
    public var endDate: String?
    /** Підстава для припинення дії запису */
    public var endDoc: String?

    public init(`id`: Int64?, code: String?, name: String?, parentCode: String?, level: Int?, details: Bool?, beginDate: String?, beginDoc: String?, endDate: String?, endDoc: String?) { 
        self.`id` = `id`
        self.code = code
        self.name = name
        self.parentCode = parentCode
        self.level = level
        self.details = details
        self.beginDate = beginDate
        self.beginDoc = beginDoc
        self.endDate = endDate
        self.endDoc = endDoc
    }
}
