//
// DisposerStatDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DisposerStatDTO

import Vapor


public final class DisposerStatDTO: Content {

    public var cntSignActs: Int64?
    public var cntSignAddendums: Int64?
    public var cntSignContracts: Int64?
    public var cntSignFines: Int64?
    public var cntSignReports: Int64?

    public init(cntSignActs: Int64?, cntSignAddendums: Int64?, cntSignContracts: Int64?, cntSignFines: Int64?, cntSignReports: Int64?) { 
        self.cntSignActs = cntSignActs
        self.cntSignAddendums = cntSignAddendums
        self.cntSignContracts = cntSignContracts
        self.cntSignFines = cntSignFines
        self.cntSignReports = cntSignReports
    }
}
