//
// DistributorRequest.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DistributorRequest

import Vapor


public final class DistributorRequest: Content {

    public var edrpou: String?
    public var empty: Bool?
    public var hasCabinet: Bool?
    public var kopfg: Int?
    public var orgEdrState: Int?
    public var organizationName: String?
    public var regionId: Int?
    public var regionIds: [Int]?

    public init(edrpou: String?, empty: Bool?, hasCabinet: Bool?, kopfg: Int?, orgEdrState: Int?, organizationName: String?, regionId: Int?, regionIds: [Int]?) { 
        self.edrpou = edrpou
        self.empty = empty
        self.hasCabinet = hasCabinet
        self.kopfg = kopfg
        self.orgEdrState = orgEdrState
        self.organizationName = organizationName
        self.regionId = regionId
        self.regionIds = regionIds
    }
}
