//
// DistributorDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DistributorDTO

import Vapor


public final class DistributorDTO: Content {

    /** Статус організації */
    public var edrState: String?
    /** ЄДРПОУ */
    public var edrpou: String?
    /** КОПФГ */
    public var kopfg: Int64?
    /** Назва організації */
    public var orgName: String?
    /** Статус кабінету */
    public var profileState: String?
    /** Область */
    public var regionName: String?

    public init(edrState: String?, edrpou: String?, kopfg: Int64?, orgName: String?, profileState: String?, regionName: String?) { 
        self.edrState = edrState
        self.edrpou = edrpou
        self.kopfg = kopfg
        self.orgName = orgName
        self.profileState = profileState
        self.regionName = regionName
    }
}
