//
// DkppDict.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DkppDict

import Vapor


public final class DkppDict: Content {

    public var code: String?
    public var codeParent: String?
    public var nameProd: String?
    public var numberSection: String?

    public init(code: String?, codeParent: String?, nameProd: String?, numberSection: String?) { 
        self.code = code
        self.codeParent = codeParent
        self.nameProd = nameProd
        self.numberSection = numberSection
    }
}
