//
// DksuDepartment.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DksuDepartment

import Vapor


public final class DksuDepartment: Content {

    public var regionCode: Int?
    public var regionName: String?

    public init(regionCode: Int?, regionName: String?) { 
        self.regionCode = regionCode
        self.regionName = regionName
    }
}
