//
// DocStat.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DocStat

import Vapor


public final class DocStat: Content {

    /** Кількість внесених звітів */
    public var cntRep: Int?
    /** К-ть внесених договорів */
    public var cntDoc: Int?
    /** К-ть внесених додатків */
    public var cntAddDoc: Int?
    /** К-ть внесених актів */
    public var cntAct: Int?
    /** К-ть внесених штрафів */
    public var cntPeny: Int?
    /** К-ть підписаних звітів */
    public var cntSignRep: Int?
    /** К-ть підписаних договорів */
    public var cntSignCont: Int?
    /** К-ть підписаних додатків */
    public var cntSignAddCont: Int?
    /** К-ть підписаних актів */
    public var cntSignAct: Int?
    /** К-ть підписаних штрафів */
    public var cntSignPeny: Int?

    public init(cntRep: Int?, cntDoc: Int?, cntAddDoc: Int?, cntAct: Int?, cntPeny: Int?, cntSignRep: Int?, cntSignCont: Int?, cntSignAddCont: Int?, cntSignAct: Int?, cntSignPeny: Int?) { 
        self.cntRep = cntRep
        self.cntDoc = cntDoc
        self.cntAddDoc = cntAddDoc
        self.cntAct = cntAct
        self.cntPeny = cntPeny
        self.cntSignRep = cntSignRep
        self.cntSignCont = cntSignCont
        self.cntSignAddCont = cntSignAddCont
        self.cntSignAct = cntSignAct
        self.cntSignPeny = cntSignPeny
    }
}
