//
// DocumentDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DocumentDTO

import Vapor


public final class DocumentDTO: Content {

    public var typeId: Int?
    /** id-документу */
    public var `id`: Int64?
    /** ЄДРПОУ-розпорядника */
    public var edrpou: String?
    /** Номер документу */
    public var documentNumber: String?
    /** Дата укладання документу */
    public var documentDate: String?
    /** Дата підписання (оприлюднення) */
    public var signDate: String?
    public var signature: SignatureDTO?
    /** Вартість документу */
    public var amount: Double?
    /** Валюта документу */
    public var currency: String?
    /** Еквівалент, грн. (для валютних документів) */
    public var currencyAmountUAH: Double?
    /** Контрагенти */
    public var contractors: [ContractorDTO]?

    public init(typeId: Int?, `id`: Int64?, edrpou: String?, documentNumber: String?, documentDate: String?, signDate: String?, signature: SignatureDTO?, amount: Double?, currency: String?, currencyAmountUAH: Double?, contractors: [ContractorDTO]?) { 
        self.typeId = typeId
        self.`id` = `id`
        self.edrpou = edrpou
        self.documentNumber = documentNumber
        self.documentDate = documentDate
        self.signDate = signDate
        self.signature = signature
        self.amount = amount
        self.currency = currency
        self.currencyAmountUAH = currencyAmountUAH
        self.contractors = contractors
    }
}
