//
// EdrState.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.EdrState

import Vapor


public final class EdrState: Content {

    public var code: Int?
    public var stateName: String?

    public init(code: Int?, stateName: String?) { 
        self.code = code
        self.stateName = stateName
    }
}
