//
// EnterpriseStatistic.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.EnterpriseStatistic

import Vapor


public final class EnterpriseStatistic: Content {

    public var docAmount: Int?
    public var edrpou: String?
    public var orgName: String?
    public var signedActs: Int?
    public var signedAddendums: Int?
    public var signedContracts: Int?
    public var signedFines: Int?
    public var signedReports: Int?

    public init(docAmount: Int?, edrpou: String?, orgName: String?, signedActs: Int?, signedAddendums: Int?, signedContracts: Int?, signedFines: Int?, signedReports: Int?) { 
        self.docAmount = docAmount
        self.edrpou = edrpou
        self.orgName = orgName
        self.signedActs = signedActs
        self.signedAddendums = signedAddendums
        self.signedContracts = signedContracts
        self.signedFines = signedFines
        self.signedReports = signedReports
    }
}
