//
// FileDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.FileDTO

import Vapor


public final class FileDTO: Content {

    public enum DocumentType: String, Content { 
        case undefined = "UNDEFINED"
        case contract = "CONTRACT"
        case addendum = "ADDENDUM"
        case act = "ACT"
        case peny = "PENY"
        case deleted = "DELETED"
    }

    public var documentDate: String?
    public var documentType: DocumentType?
    public var finishDate: String?

    public init(documentDate: String?, documentType: DocumentType?, finishDate: String?) { 
        self.documentDate = documentDate
        self.documentType = documentType
        self.finishDate = finishDate
    }
}
