//
// File.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.File

import Vapor


public final class File: Content {

    public var absolute: Bool?
    public var absoluteFile: File?
    public var absolutePath: String?
    public var canonicalFile: File?
    public var canonicalPath: String?
    public var directory: Bool?
    public var file: Bool?
    public var freeSpace: Int64?
    public var hidden: Bool?
    public var name: String?
    public var parent: String?
    public var parentFile: File?
    public var path: String?
    public var totalSpace: Int64?
    public var usableSpace: Int64?

    public init(absolute: Bool?, absoluteFile: File?, absolutePath: String?, canonicalFile: File?, canonicalPath: String?, directory: Bool?, file: Bool?, freeSpace: Int64?, hidden: Bool?, name: String?, parent: String?, parentFile: File?, path: String?, totalSpace: Int64?, usableSpace: Int64?) { 
        self.absolute = absolute
        self.absoluteFile = absoluteFile
        self.absolutePath = absolutePath
        self.canonicalFile = canonicalFile
        self.canonicalPath = canonicalPath
        self.directory = directory
        self.file = file
        self.freeSpace = freeSpace
        self.hidden = hidden
        self.name = name
        self.parent = parent
        self.parentFile = parentFile
        self.path = path
        self.totalSpace = totalSpace
        self.usableSpace = usableSpace
    }
}
