//
// InputStream.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.InputStream

import Vapor


public final class InputStream: Content {

}
