//
// InputStreamResource.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.InputStreamResource

import Vapor


public final class InputStreamResource: Content {

    public var `description`: String?
    public var file: File?
    public var filename: String?
    public var inputStream: InputStream?
    public var `open`: Bool?
    public var readable: Bool?
    public var uri: URI?
    public var url: ModelURL?

    public init(`description`: String?, file: File?, filename: String?, inputStream: InputStream?, `open`: Bool?, readable: Bool?, uri: URI?, url: ModelURL?) { 
        self.`description` = `description`
        self.file = file
        self.filename = filename
        self.inputStream = inputStream
        self.`open` = `open`
        self.readable = readable
        self.uri = uri
        self.url = url
    }
}
