//
// IterableEdrState.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.IterableEdrState

import Vapor


public final class IterableEdrState: Content {

}
