//
// Koatuu.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Koatuu

import Vapor


public final class Koatuu: Content {

    public var code: String?
    public var name: String?
    public var regionId: Int?

    public init(code: String?, name: String?, regionId: Int?) { 
        self.code = code
        self.name = name
        self.regionId = regionId
    }
}
