//
// KopfgDict.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.KopfgDict

import Vapor


public final class KopfgDict: Content {

    public var kopfgCode: String?
    public var kopfgName: String?
    public var kopfgParent: String?

    public init(kopfgCode: String?, kopfgName: String?, kopfgParent: String?) { 
        self.kopfgCode = kopfgCode
        self.kopfgName = kopfgName
        self.kopfgParent = kopfgParent
    }
}
