//
// Kopfg.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Kopfg

import Vapor


public final class Kopfg: Content {

    public var `id`: String?
    public var title: String?

    public init(`id`: String?, title: String?) { 
        self.`id` = `id`
        self.title = title
    }
}
