//
// KopfgStat.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.KopfgStat

import Vapor


public final class KopfgStat: Content {

}
