//
// KopfgGroupedStat.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.KopfgGroupedStat

import Vapor


public final class KopfgGroupedStat: Content {

    public var count: Int?
    public var kopfg: Kopfg?
    public var parts: [KopfgStat]?

    public init(count: Int?, kopfg: Kopfg?, parts: [KopfgStat]?) { 
        self.count = count
        self.kopfg = kopfg
        self.parts = parts
    }
}
