//
// KvedDict.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.KvedDict

import Vapor


public final class KvedDict: Content {

    public var availability: Int?
    public var kvedCode: String?
    public var kvedName: String?
    public var kvedParent: String?

    public init(availability: Int?, kvedCode: String?, kvedName: String?, kvedParent: String?) { 
        self.availability = availability
        self.kvedCode = kvedCode
        self.kvedName = kvedName
        self.kvedParent = kvedParent
    }
}
