//
// LastLoadDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.LastLoadDTO

import Vapor


public final class LastLoadDTO: Content {

    public var lastLoad: String?
    public var sourceId: Int?
    public var sourceName: String?

    public init(lastLoad: String?, sourceId: Int?, sourceName: String?) { 
        self.lastLoad = lastLoad
        self.sourceId = sourceId
        self.sourceName = sourceName
    }
}
