//
// LegendDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.LegendDTO

import Vapor


public final class LegendDTO: Content {

    public var legend: String?
    public var regions: [Int]?

    public init(legend: String?, regions: [Int]?) { 
        self.legend = legend
        self.regions = regions
    }
}
