//
// ModelURL.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ModelURL

import Vapor


public final class ModelURL: Content {

    public var authority: String?
    public var content: Any?
    public var defaultPort: Int?
    public var file: String?
    public var host: String?
    public var path: String?
    public var port: Int?
    public var `protocol`: String?
    public var query: String?
    public var ref: String?
    public var userInfo: String?

    public init(authority: String?, content: Any?, defaultPort: Int?, file: String?, host: String?, path: String?, port: Int?, `protocol`: String?, query: String?, ref: String?, userInfo: String?) { 
        self.authority = authority
        self.content = content
        self.defaultPort = defaultPort
        self.file = file
        self.host = host
        self.path = path
        self.port = port
        self.`protocol` = `protocol`
        self.query = query
        self.ref = ref
        self.userInfo = userInfo
    }
}
