//
// NextLoadDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.NextLoadDTO

import Vapor


public final class NextLoadDTO: Content {

    public var nextload: String?

    public init(nextload: String?) { 
        self.nextload = nextload
    }
}
