//
// OrganizationGeneralDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.OrganizationGeneralDTO

import Vapor


public final class OrganizationGeneralDTO: Content {

    public var address: AddressDTO?
    public var director: PersonDTO?
    public var edrpou: String?
    public var fullName: String?
    public var koatuu: String?
    public var shortName: String?

    public init(address: AddressDTO?, director: PersonDTO?, edrpou: String?, fullName: String?, koatuu: String?, shortName: String?) { 
        self.address = address
        self.director = director
        self.edrpou = edrpou
        self.fullName = fullName
        self.koatuu = koatuu
        self.shortName = shortName
    }
}
