//
// OrganizationTypesDict.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.OrganizationTypesDict

import Vapor


public final class OrganizationTypesDict: Content {

    public var code: String?
    public var `id`: Int?
    public var name: String?

    public init(code: String?, `id`: Int?, name: String?) { 
        self.code = code
        self.`id` = `id`
        self.name = name
    }
}
