//
// PagedRequestVoid.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PagedRequestVoid

import Vapor


public final class PagedRequestVoid: Content {

    /** Номер сторінки */
    public var page: Int?
    /** Кількість елементів на сторінці */
    public var pageSize: Int?

    public init(page: Int?, pageSize: Int?) { 
        self.page = page
        self.pageSize = pageSize
    }
}
