//
// PagedRequestDistributorRequest.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PagedRequestDistributorRequest

import Vapor


public final class PagedRequestDistributorRequest: Content {

    public var query: DistributorRequest?
    /** Номер сторінки */
    public var page: Int?
    /** Кількість елементів на сторінці */
    public var pageSize: Int?

    public init(query: DistributorRequest?, page: Int?, pageSize: Int?) { 
        self.query = query
        self.page = page
        self.pageSize = pageSize
    }
}
