//
// PageResultEnterpriseStatistic.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PageResultEnterpriseStatistic

import Vapor


public final class PageResultEnterpriseStatistic: Content {

    /** Список елементів */
    public var elements: [EnterpriseStatistic]?
    /** Номер сторінки */
    public var number: Int?
    public var pageSize: Int?
    /** Елементів на сторінці */
    public var size: Int?
    /** Всього документів */
    public var totalElements: Int64?
    /** Всього сторінок */
    public var totalPages: Int64?

    public init(elements: [EnterpriseStatistic]?, number: Int?, pageSize: Int?, size: Int?, totalElements: Int64?, totalPages: Int64?) { 
        self.elements = elements
        self.number = number
        self.pageSize = pageSize
        self.size = size
        self.totalElements = totalElements
        self.totalPages = totalPages
    }
}
