//
// PaymentData.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PaymentData

import Vapor


public final class PaymentData: Content {

}
