//
// PersonDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PersonDTO

import Vapor


public final class PersonDTO: Content {

    public var firstName: String?
    public var lastName: String?
    public var middleName: String?

    public init(firstName: String?, lastName: String?, middleName: String?) { 
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
    }
}
