//
// Procurement.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Procurement

import Vapor


public final class Procurement: Content {

    /** CPV CODE */
    public var cpvCode: String?
    /** Name of Item */
    public var nameUa: String?

    public init(cpvCode: String?, nameUa: String?) { 
        self.cpvCode = cpvCode
        self.nameUa = nameUa
    }
}
