//
// RegionStatDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.RegionStatDTO

import Vapor


public final class RegionStatDTO: Content {

    public var count: Int?
    public var `id`: Int?
    public var name: String?
    public var sum: Double?

    public init(count: Int?, `id`: Int?, name: String?, sum: Double?) { 
        self.count = count
        self.`id` = `id`
        self.name = name
        self.sum = sum
    }
}
