//
// Regions.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Regions

import Vapor


public final class Regions: Content {

    public var koatuu: String?
    public var regionCode: Int?
    public var regionName: String?

    public init(koatuu: String?, regionCode: Int?, regionName: String?) { 
        self.koatuu = koatuu
        self.regionCode = regionCode
        self.regionName = regionName
    }
}
