//
// RegionKopfgStat.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.RegionKopfgStat

import Vapor


public final class RegionKopfgStat: Content {

    public var koatuu: Koatuu?
    public var stat: [KopfgGroupedStat]?

    public init(koatuu: Koatuu?, stat: [KopfgGroupedStat]?) { 
        self.koatuu = koatuu
        self.stat = stat
    }
}
