//
// ReportApiCodeDto.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ReportApiCodeDto

import Vapor


public final class ReportApiCodeDto: Content {

    public var code: String?
    public var reportTypeId: Int64?
    public var shortTitle: String?
    public var title: String?
    public var type: String?

    public init(code: String?, reportTypeId: Int64?, shortTitle: String?, title: String?, type: String?) { 
        self.code = code
        self.reportTypeId = reportTypeId
        self.shortTitle = shortTitle
        self.title = title
        self.type = type
    }
}
