//
// ShortAddressDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ShortAddressDTO

import Vapor


public final class ShortAddressDTO: Content {

    public var city: String?
    public var district: String?
    public var districtCity: String?
    public var `prefix`: String?
    public var regionId: Int?
    public var regionName: String?

    public init(city: String?, district: String?, districtCity: String?, `prefix`: String?, regionId: Int?, regionName: String?) { 
        self.city = city
        self.district = district
        self.districtCity = districtCity
        self.`prefix` = `prefix`
        self.regionId = regionId
        self.regionName = regionName
    }
}
