//
// SignatureDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SignatureDTO

import Vapor


public final class SignatureDTO: Content {

    public var caAddress: String?

    public init(caAddress: String?) { 
        self.caAddress = caAddress
    }
}
