//
// SpecificationDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SpecificationDTO

import Vapor


public final class SpecificationDTO: Content {

    public var cpvCode: String?
    public var itemCost: Double?
    public var itemCount: Double?
    public var itemDimension: String?
    public var specCode: String?
    public var specificationName: String?

    public init(cpvCode: String?, itemCost: Double?, itemCount: Double?, itemDimension: String?, specCode: String?, specificationName: String?) { 
        self.cpvCode = cpvCode
        self.itemCost = itemCost
        self.itemCount = itemCount
        self.itemDimension = itemDimension
        self.specCode = specCode
        self.specificationName = specificationName
    }
}
