//
// StatDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.StatDTO

import Vapor


public final class StatDTO: Content {

    public var amount: Float?
    public var name: String?
    public var percents: Float?

    public init(amount: Float?, name: String?, percents: Float?) { 
        self.amount = amount
        self.name = name
        self.percents = percents
    }
}
