//
// TopTransaction.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.TopTransaction

import Vapor


public final class TopTransaction: Content {

    public var amount: Decimal?
    public var `id`: Int64?
    public var payerEdrpou: String?
    public var payerName: String?
    public var reciptEdrpou: String?
    public var reciptName: String?
    public var transDate: String?

    public init(amount: Decimal?, `id`: Int64?, payerEdrpou: String?, payerName: String?, reciptEdrpou: String?, reciptName: String?, transDate: String?) { 
        self.amount = amount
        self.`id` = `id`
        self.payerEdrpou = payerEdrpou
        self.payerName = payerName
        self.reciptEdrpou = reciptEdrpou
        self.reciptName = reciptName
        self.transDate = transDate
    }
}
