//
// TransStatDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.TransStatDTO

import Vapor


public final class TransStatDTO: Content {

    public var from: String?
    public var regions: [RegionStatDTO]?
    public var reqDate: String?
    public var totalCount: Int?
    public var totalSum: Double?

    public init(from: String?, regions: [RegionStatDTO]?, reqDate: String?, totalCount: Int?, totalSum: Double?) { 
        self.from = from
        self.regions = regions
        self.reqDate = reqDate
        self.totalCount = totalCount
        self.totalSum = totalSum
    }
}
