//
// TransactionDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.TransactionDTO

import Vapor


public final class TransactionDTO: Content {

    /** Унікальний ідентифікатор */
    public var `id`: Int64?
    /** Код розрахункового документа */
    public var docVob: String?
    /** Тип розрахункового документа */
    public var docVobName: String?
    /** Номер розрахункового документа */
    public var docNumber: String?
    /** Дата складання */
    public var docDate: String?
    /** Дата валютування */
    public var docVDate: String?
    /** Дата оплати */
    public var transDate: String?
    /** Сума */
    public var amount: Decimal?
    /** Сума в копійках */
    public var amountCop: Int64?
    /** Валюта */
    public var currency: String?
    /** Код платника */
    public var payerEdrpou: String?
    /** Найменування платника */
    public var payerName: String?
    /** Рахунок платника */
    public var payerAccount: String?
    /** Код банку платника */
    public var payerMfo: String?
    /** Найменування банку платника */
    public var payerBank: String?
    /** Код одержувача */
    public var reciptEdrpou: String?
    /** Найменування одержувача */
    public var reciptName: String?
    /** Рахунок одержувача */
    public var reciptAccount: String?
    /** Найменування банку одержувача */
    public var reciptBank: String?
    /** Код банку одержувача */
    public var reciptMfo: String?
    /** Призначення платежу */
    public var paymentDetails: String?
    /** Додатковий реквізит */
    public var docAddAttr: String?
    /** Регіон */
    public var regionId: Int?
    /** Тип платіжної системи */
    public var paymentType: String?
    public var paymentData: PaymentData?
    /** Ідентифікатор джерела даних */
    public var sourceId: Int?
    /** Джерело даних */
    public var sourceName: String?
    /** КЕКВ */
    public var kekv: Int64?
    /** КПКВК */
    public var kpk: String?
    /** Ідентифікатор договору про закупівлю */
    public var contractId: String?
    /** Ідентифікатор закупівлі (Prozorro) */
    public var contractNumber: String?
    /** Код бюджету */
    public var budgetCode: String?

    public init(`id`: Int64?, docVob: String?, docVobName: String?, docNumber: String?, docDate: String?, docVDate: String?, transDate: String?, amount: Decimal?, amountCop: Int64?, currency: String?, payerEdrpou: String?, payerName: String?, payerAccount: String?, payerMfo: String?, payerBank: String?, reciptEdrpou: String?, reciptName: String?, reciptAccount: String?, reciptBank: String?, reciptMfo: String?, paymentDetails: String?, docAddAttr: String?, regionId: Int?, paymentType: String?, paymentData: PaymentData?, sourceId: Int?, sourceName: String?, kekv: Int64?, kpk: String?, contractId: String?, contractNumber: String?, budgetCode: String?) { 
        self.`id` = `id`
        self.docVob = docVob
        self.docVobName = docVobName
        self.docNumber = docNumber
        self.docDate = docDate
        self.docVDate = docVDate
        self.transDate = transDate
        self.amount = amount
        self.amountCop = amountCop
        self.currency = currency
        self.payerEdrpou = payerEdrpou
        self.payerName = payerName
        self.payerAccount = payerAccount
        self.payerMfo = payerMfo
        self.payerBank = payerBank
        self.reciptEdrpou = reciptEdrpou
        self.reciptName = reciptName
        self.reciptAccount = reciptAccount
        self.reciptBank = reciptBank
        self.reciptMfo = reciptMfo
        self.paymentDetails = paymentDetails
        self.docAddAttr = docAddAttr
        self.regionId = regionId
        self.paymentType = paymentType
        self.paymentData = paymentData
        self.sourceId = sourceId
        self.sourceName = sourceName
        self.kekv = kekv
        self.kpk = kpk
        self.contractId = contractId
        self.contractNumber = contractNumber
        self.budgetCode = budgetCode
    }
}
