//
// TransactionsPageDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.TransactionsPageDTO

import Vapor


public final class TransactionsPageDTO: Content {

    /** Усього транзакцій за запитом */
    public var count: Int64?
    /** Сторінка */
    public var page: Int?
    /** Транзакцій на сторінці */
    public var pageSize: Int?
    /** Транзакції */
    public var transactions: [TransactionDTO]?

    public init(count: Int64?, page: Int?, pageSize: Int?, transactions: [TransactionDTO]?) { 
        self.count = count
        self.page = page
        self.pageSize = pageSize
        self.transactions = transactions
    }
}
