//
// URI.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.URI

import Vapor


public final class URI: Content {

    public var absolute: Bool?
    public var authority: String?
    public var fragment: String?
    public var host: String?
    public var opaque: Bool?
    public var path: String?
    public var port: Int?
    public var query: String?
    public var rawAuthority: String?
    public var rawFragment: String?
    public var rawPath: String?
    public var rawQuery: String?
    public var rawSchemeSpecificPart: String?
    public var rawUserInfo: String?
    public var scheme: String?
    public var schemeSpecificPart: String?
    public var userInfo: String?

    public init(absolute: Bool?, authority: String?, fragment: String?, host: String?, opaque: Bool?, path: String?, port: Int?, query: String?, rawAuthority: String?, rawFragment: String?, rawPath: String?, rawQuery: String?, rawSchemeSpecificPart: String?, rawUserInfo: String?, scheme: String?, schemeSpecificPart: String?, userInfo: String?) { 
        self.absolute = absolute
        self.authority = authority
        self.fragment = fragment
        self.host = host
        self.opaque = opaque
        self.path = path
        self.port = port
        self.query = query
        self.rawAuthority = rawAuthority
        self.rawFragment = rawFragment
        self.rawPath = rawPath
        self.rawQuery = rawQuery
        self.rawSchemeSpecificPart = rawSchemeSpecificPart
        self.rawUserInfo = rawUserInfo
        self.scheme = scheme
        self.schemeSpecificPart = schemeSpecificPart
        self.userInfo = userInfo
    }
}
